version: '3.8'

services:
 
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:5525@db:5432/fake_detector?connect_timeout=5&keepalives=1"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fakenewsdetetctor_fakenewsdetetctor
    restart: unless-stopped
    healthcheck:  # Healthcheck for the backend
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: 5525
      POSTGRES_DB: fake_detector
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fake_detector"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fakenewsdetetctor_fakenewsdetetctor
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fakenewsdetetctor_fakenewsdetetctor
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  fakenewsdetetctor_fakenewsdetetctor:
    driver: bridge
